import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY  // service role bypasses RLS for server-side ops
)

const resend = new Resend(process.env.RESEND_API_KEY)

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { listId, ownerEmail, ownerName, sharedWithEmail, permission = 'edit' } = req.body

  if (!listId || !ownerEmail || !sharedWithEmail) {
    return res.status(400).json({ error: 'Missing required fields' })
  }

  if (ownerEmail.toLowerCase() === sharedWithEmail.toLowerCase()) {
    return res.status(400).json({ error: 'You cannot share a list with yourself' })
  }

  try {
    // 1. Get the list name
    const { data: list, error: listError } = await supabase
      .from('lists')
      .select('name, user_id')
      .eq('id', listId)
      .single()

    if (listError || !list) {
      return res.status(404).json({ error: 'List not found' })
    }

    // 2. Create the share record (token is auto-generated by DB default)
    const { data: share, error: shareError } = await supabase
      .from('list_shares')
      .insert({
        list_id: listId,
        owner_id: list.user_id,
        shared_with_email: sharedWithEmail.toLowerCase().trim(),
        permission,
      })
      .select()
      .single()

    if (shareError) {
      // Unique constraint hit — already invited
      if (shareError.code === '23505') {
        return res.status(409).json({ error: 'This person has already been invited to this list' })
      }
      throw shareError
    }

    // 3. Build the invite link
    const inviteUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite?token=${share.token}`

    // 4. Send the invite email via Resend
    const fromName = ownerName || ownerEmail.split('@')[0]
    const listName = list.name

    await resend.emails.send({
      from: 'List. <noreply@listdot.app>',
      to: sharedWithEmail,
      subject: `${fromName} shared a list with you on List.`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
        </head>
        <body style="margin:0;padding:0;background:#f7f4ef;font-family:Inter,sans-serif;">
          <table width="100%" cellpadding="0" cellspacing="0" style="background:#f7f4ef;padding:40px 20px;">
            <tr><td align="center">
              <table width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;">

                <!-- Logo -->
                <tr><td style="padding-bottom:32px;text-align:center;">
                  <span style="font-family:'Plus Jakarta Sans',sans-serif;font-weight:800;font-size:28px;color:#0f1a14;letter-spacing:-1px;">
                    List<span style="color:#0f6644;">.</span>
                  </span>
                </td></tr>

                <!-- Card -->
                <tr><td style="background:#ffffff;border-radius:16px;border:1.5px solid #ede8df;padding:40px;box-shadow:0 4px 20px rgba(0,0,0,0.06);">

                  <p style="margin:0 0 8px;font-size:13px;font-weight:600;color:#0f6644;letter-spacing:0.1em;text-transform:uppercase;">You've been invited</p>
                  <h1 style="margin:0 0 16px;font-size:24px;font-weight:800;color:#0f1a14;letter-spacing:-0.5px;line-height:1.2;">
                    ${fromName} shared<br/>"${listName}" with you
                  </h1>
                  <p style="margin:0 0 32px;font-size:15px;color:#4a4235;line-height:1.6;">
                    You've been given <strong>${permission}</strong> access to this list on List. — the focused productivity app built around the Ivy Lee method.
                  </p>

                  <!-- CTA Button -->
                  <table width="100%" cellpadding="0" cellspacing="0">
                    <tr><td align="center" style="padding-bottom:32px;">
                      <a href="${inviteUrl}"
                        style="display:inline-block;background:#0f6644;color:#ffffff;font-size:15px;font-weight:600;padding:14px 32px;border-radius:10px;text-decoration:none;box-shadow:0 4px 16px rgba(15,102,68,0.3);">
                        Accept invite →
                      </a>
                    </td></tr>
                  </table>

                  <p style="margin:0;font-size:12px;color:#9a8f7a;text-align:center;line-height:1.6;">
                    Or copy this link into your browser:<br/>
                    <span style="color:#0f6644;word-break:break-all;">${inviteUrl}</span>
                  </p>

                </td></tr>

                <!-- Footer -->
                <tr><td style="padding-top:24px;text-align:center;">
                  <p style="margin:0;font-size:12px;color:#9a8f7a;">
                    List. · <a href="https://listdot.app" style="color:#9a8f7a;">listdot.app</a>
                  </p>
                  <p style="margin:4px 0 0;font-size:11px;color:#c0b8a8;">
                    If you weren't expecting this, you can safely ignore it.
                  </p>
                </td></tr>

              </table>
            </td></tr>
          </table>
        </body>
        </html>
      `,
    })

    return res.status(200).json({ success: true, shareId: share.id })

  } catch (err) {
    console.error('share-list error:', err)
    return res.status(500).json({ error: 'Something went wrong. Please try again.' })
  }
}
